services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      - my_network


networks:
  my_network:
    name: my_network
    driver: bridge